### ISSUE TITLE
Crash in jalv.gtk3

### ISSUE THREAD

**Issue by sjaehn** [sjaehn/BOops#13]
Crash with jalv.gtk3 (1.6.4). Happens sometimes, not very often. `gdb jalv.gtk3 core` output: 

```
#0  BOopsGUI::port_event(unsigned int, unsigned int, unsigned int, void const*)
    (this=
    0x5569cd7c3430, port=1065353216, buffer_size=0, format=0, buffer=0x5569ce69aaf0) at ../../src/BOopsGUI.cpp:694
#1  0x00007f43d8d375a0 in port_event(LV2UI_Handle, uint32_t, uint32_t, uint32_t, void const*)
    (ui=0x5569cd7c3430, port_index=1065353216, buffer_size=0, format=0, buffer=0x5569ce69aaf0) at ../../src/BOopsGUI.cpp:2766
#2  0x00005569cbab7790 in  ()
#3  0x00005569cbaaf4f8 in  ()
#4  0x00007f43e31fca08 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f43e31fbe6e in g_main_context_dispatch ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007f43e31fc220 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007f43e31fc513 in g_main_loop_run ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007f43e368637d in gtk_main () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00005569cbab7bd7 in  ()
#10 0x00005569cbaad768 in  ()
#11 0x00007f43e2fdf0b3 in __libc_start_main (main=
    0x5569cbaad690, argc=2, argv=0x7ffe6021e6d8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe6021e6c8)
    at ../csu/libc-start.c:308
--Type <RET> for more, q to quit, c to continue without paging--
#12 0x00005569cbaad7ce in  ()
```

Very interesting point: `port_index = 1065353216` (= 0x3f800000 = 1.0f). Whereas `buffer_size = 0`.

**Comment by sjaehn** [comment]
Likely a bug in an older version of jalv (?). Can't reproduce it with the current jalv master. Anyway, now check for valid ports in 9c028b34ef004eb5555b436fcb69679ea2186664 .

**Comment by sjaehn** [comment]
No, it's not fixed. I got sth. similar again. Same situation: directly after / during changing the preset:

```
(gdb) bt
#0  0x00007fc495624a6a in BOopsGUI::port_event(unsigned int, unsigned int, unsigned int, void const*) (this=
    0x55ac67c24a70, port=63, buffer_size=0, format=0, buffer=0x0)
    at ../../src/BOopsGUI.cpp:697
#1  0x00007fc49563460a in port_event(LV2UI_Handle, uint32_t, uint32_t, uint32_t, void const*)
    (ui=0x55ac67c24a70, port_index=63, buffer_size=0, format=0, buffer=0x0)
    at ../../src/BOopsGUI.cpp:2778
#2  0x000055ac6604336b in jalv_ui_port_event
    (jalv=0x7ffe56da6a20, port_index=63, buffer_size=0, protocol=0, buffer=0x0)
    at ../src/jalv_gtk.c:708
#3  0x000055ac66039cac in jalv_update (jalv=0x7ffe56da6a20)
    at ../src/jalv.c:690
#4  0x00007fc4acf3fa08 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fc4acf3ee6e in g_main_context_dispatch ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007fc4acf3f220 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007fc4acf3f513 in g_main_loop_run ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007fc4ad3c937d in gtk_main () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x000055ac66045400 in jalv_open_ui (jalv=0x7ffe56da6a20)
    at ../src/jalv_gtk.c:1292
#10 0x000055ac6603c6fa in main (argc=2, argv=0x7ffe56da71a8)
--Type <RET> for more, q to quit, c to continue without paging--
    at ../src/jalv.c:1337
```

This time a valid port number but an invalid buffer (nullptr).

Within frame 3:
```
(gdb) frame 3
#3  0x000055ac66039cac in jalv_update (jalv=0x7ffe56da6a20)
    at ../src/jalv.c:690
690			jalv_ui_port_event(jalv, ev.index, ev.size, ev.protocol, buf);
(gdb) print i
$1 = 0
(gdb) print space
$2 = 4809
(gdb) print sizeof(ev)
$3 = 12
(gdb) print ev.size
$4 = 0
(gdb) print ev
$5 = {index = 63, protocol = 0, size = 0, body = 0x7ffe56da6838 ""}
```
